{
  "tweet": {
    "edit_info": {
      "initial": {
        "editTweetIds": [
          "1490402366599745538"
        ],
        "editableUntil": "2022-02-06T20:09:49.191Z",
        "editsRemaining": "5",
        "isEditEligible": true
      }
    },
    "retweeted": false,
    "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
    "entities": {
      "hashtags": [],
      "symbols": [],
      "user_mentions": [],
      "urls": []
    },
    "display_text_range": [
      "0",
      "261"
    ],
    "favorite_count": "3",
    "in_reply_to_status_id_str": "1490402365832237056",
    "id_str": "1490402366599745538",
    "in_reply_to_user_id": "601449312",
    "truncated": false,
    "retweet_count": "0",
    "id": "1490402366599745538",
    "in_reply_to_status_id": "1490402365832237056",
    "created_at": "Sun Feb 06 19:09:49 +0000 2022",
    "favorited": false,
    "full_text": "The problem here is NOT one of unit testing. If the programmer knew this problem was possible, they would have called the safe version in the first place, and even THEN they would not have unit tested and duplicated the unit tests the safe function already has.",
    "lang": "en",
    "in_reply_to_screen_name": "zemnmez",
    "in_reply_to_user_id_str": "601449312"
  }
}